/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.mydsl.generator;

/* @Aspect() */@SuppressWarnings("all")
public class TransitionAspect {
  /* @Step
   */public void fire() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nThe method or field _self is undefined"
      + "\nname cannot be resolved"
      + "\ntgt cannot be resolved"
      + "\nname cannot be resolved"
      + "\nsrc cannot be resolved"
      + "\nfsm cannot be resolved"
      + "\ncurrentState cannot be resolved"
      + "\ntgt cannot be resolved"
      + "\noutputBuffer cannot be resolved"
      + "\nenqueue cannot be resolved"
      + "\naction cannot be resolved"
      + "\nconsummedString cannot be resolved"
      + "\nconsummedString cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nunderProcessTrigger cannot be resolved");
  }
}
